### ISSUE TITLE
BACKPORT TO 1.20 AND MY LIFE IS YOURS!!!

### ISSUE THREAD

**Issue by PixitOwO** [Traben-0/flowing_fluids#1]
Really love what you are doing and have planned, especially with create compats. I saw you already said you were possibly back porting to 1.20, and wanted to post so you know some people would use it.

**Comment by candied-apple** [comment]
yes please this would be so fun with create in 1.20.1

**Comment by Traben-0** [comment]
I'll move it to the top of my list for the mod :)

**Comment by Traben-0** [comment]
done
