### ISSUE TITLE
[Bug] Crash when joining minecraft server

### ISSUE THREAD

**Issue by McSnurtle** [Traben-0/flowing_fluids#13]
I am self-hosting a heavily modded server, and I crash when joining (the crash just started after adding the mod to the server). The server does not crash, nor report any errors. Here is the crash report:

[crash-2024-11-08_16.21.52-client.txt](https://github.com/user-attachments/files/17684283/crash-2024-11-08_16.21.52-client.txt)

**Comment by Traben-0** [comment]
The source of this is known and will be worked on this week alongside also doing a 1.21.3 update
