### ISSUE TITLE
NeoForge - 1.21.1 - 0.3 not work with sodium

### ISSUE THREAD

**Issue by AlximikXD** [Traben-0/flowing_fluids#19]
On version **1.21.1** of **NeoForge 21.1.77** using **Sodium 0.6.0 Beta 4 for NeoForge**, when entering the world, a crash occurs
**[1.21.1] Embeddium 1.0.11** after updating to version **0.3** works
[crash-2024-11-15_14.31.42-client.txt](https://github.com/user-attachments/files/17775418/crash-2024-11-15_14.31.42-client.txt)

**Comment by Traben-0** [comment]
fixed
