### ISSUE TITLE
Setting for block range of flow over edges

### ISSUE THREAD

**Issue by smiRaphi** [Traben-0/flowing_fluids#2]
It'd be nice to have an option to set the range to something higher than 4.

**Comment by Traben-0** [comment]
that is an option i plan to make a setting for, though increasing it by more than a couple is not a great idea

keep in mind a distance of 4 means water placed on flat ground needs to check 40 blocks below it's current level as well as roughly 160 ways of potentially flowing to those blocks. and this does not scale linearly with higher numbers

**Comment by Traben-0** [comment]
i added the option and its even more ridiculous than i initially thought, i have to cap the resulting search distance to 8 or else the world just freezes, likewise this means the gains from toning it down to 2 or 3 are also nice

**Comment by smiRaphi** [comment]
thank you!
