### ISSUE TITLE
can't run the game with version 0.2

### ISSUE THREAD

**Issue by juyoung9653** [Traben-0/flowing_fluids#5]
[crash-2024-10-08_14.12.31-client.txt](https://github.com/user-attachments/files/17288167/crash-2024-10-08_14.12.31-client.txt)
[crash-2024-10-08_14.02.16-client.txt](https://github.com/user-attachments/files/17288135/crash-2024-10-08_14.02.16-client.txt)
I only used this mod
click create a new world, the game will end.

**Comment by juyoung9653** [comment]
It worked after I reconnected.

**Comment by juyoung9653** [comment]
__

**Comment by Traben-0** [comment]
reopened?

**Comment by juyoung9653** [comment]
I mistakenly thought that the crashing when creating a world was the crashing when logging in. And oh? Does it work? and closed it

**Comment by Traben-0** [comment]
making a new world works for me

**Comment by Traben-0** [comment]
trying forge now

**Comment by Traben-0** [comment]
i've got it ill see why this happens

**Comment by Traben-0** [comment]
ok fix will be up soon

**Comment by juyoung9653** [comment]
good :)

**Comment by Traben-0** [comment]
done

**Comment by juyoung9653** [comment]
0.2.1 does not work with embeddium.. 
I can't access the world
[crash-2024-10-08_15.10.14-client.txt](https://github.com/user-attachments/files/17288765/crash-2024-10-08_15.10.14-client.txt)
